services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin123"
      MYSQL_DATABASE: "ignite-challenge-02"
      MYSQL_ROOT_PASSWORD: "admin123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
